name : Docker Container
on : push
jobs:
  Node-Container:
    name: Node Docker
    runs-on: ubuntu-latest
    container : 
     image: node:16-alpine3.11
    steps:
      - name: Log Node Version
        run: |
         node -v
         cat /etc/os-release 
         
       
  GO_Lan-Container:
    name: GO Docker
    runs-on: ubuntu-latest
    container : 
     image: golang:1.15.13-alpine3.13
    steps:
      - name: Log Go Lang Version
        run: |
         go version
         cat /etc/os-release

  RUN_NODE_AAP_WITH_MONGO:  
    name: run app and mongodb service
    runs-on: ubuntu-latest
    services:
      app:
        image: balajidongare08/node-app
        ports:
         - 3001:3000
      mongo:
        image: mongo
        ports:
         - "27017:27017"
    steps:
      - name: Post a user
        run : "curl --location --request POST 'http://localhost:3001/api/users' \
              --header 'Content-Type: application/json' \
              --data-raw '{ \"username\":\"Balaji\", \"address\": \"pune\"}'"  
      - name: Get Users
        run :  "curl --location --request GET 'http://localhost:3001/api/users' \
              --header 'Content-Type: application/json'"         
   