name: Git Env Vars and create issue on commit
on: push
jobs:
  create-commit:
    name: Create issue using REST-API
    runs-on: ubuntu-latest
    steps:
     - name: Create issue
       run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
     - name: Create a file and push it to repp
       run: |
         pwd
         ls -a
         git init 
         git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"     
         git config --global.email "bob@bot.com"
         git config --global.name "bob"
         git fetch
         git checkout master
         git branch --set-upstream-to=origin/master
         git pull
         pwd 
         ls -a
         echo $RANDOM >> Random.txt
         ls -a
         git add -A
         git commit -m "feat: Creating aa file and pushing"
         git push
        #  git remote add origin "git@github.com:balaji-dongare/Github-Action-GO.git" - when you configured you ssh key to github on line no #24
             