name: Matrix
on : push
jobs:
   node-version:
    name: get node version
    runs-on: ubuntu-latest
    steps:
      - name: Log Node Version
        run: node -v
      - name: Update version to 6
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '6' 
      - name: Log Node Version after update
        run: node -v       