name: Matrix
on : push
jobs:
   node-version:
    strategy:
     matrix:
       os: [ubuntu-latest,macos-latest, windows-latest]
       node-version: [6,8,12]   
    name: get node version
    runs-on: ${{matrix.os}}
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v2
        with:
            node-version: ${{matrix.node-version}}
      - name: Log Node Version after update
        run: node -v       